"""add_question_parent_child

Revision ID: 22915b61a20a
Revises: 9f4cfada30ca
Create Date: 2025-12-21 11:22:13.744720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22915b61a20a'
down_revision: Union[str, Sequence[str], None] = '9f4cfada30ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_questions_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key(None, 'questions', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_questions_parent_id'))
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
