"""add_subject_id_to_question

Revision ID: 830cc1d218ea
Revises: b31bcd4d8888
Create Date: 2025-12-12 10:49:11.794051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '830cc1d218ea'
down_revision: Union[str, Sequence[str], None] = 'b31bcd4d8888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('draft', 'pending', 'published', 'archived'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'published'"))
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('draft', 'pending', 'published', 'archived'),
               existing_nullable=False,
               existing_server_default=sa.text("'published'"))
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
