"""add mode to import_task

Revision ID: 9129292867de
Revises: f02a7f680a4b
Create Date: 2025-12-23 22:01:43.736665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9129292867de'
down_revision: Union[str, Sequence[str], None] = 'f02a7f680a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_tasks', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
