"""rename_category_to_knowledge_point

Revision ID: add4a1d0b0b1
Revises: ffa814ff3031
Create Date: 2025-12-14 12:56:12.228221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'add4a1d0b0b1'
down_revision: Union[str, Sequence[str], None] = 'ffa814ff3031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'slug', name='uq_knowledge_point_subject_slug')
    )
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_points_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_points_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_points_slug'), ['slug'], unique=False)

    op.create_table('question_knowledge_points',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'knowledge_point_id')
    )
    
    op.drop_table('question_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('subject_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('categories_ibfk_4')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('categories_ibfk_1')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('categories_ibfk_2')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('categories_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_category_subject_slug'), ['subject_id', 'slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('question_categories',
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('question_categories_ibfk_1')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('question_categories_ibfk_2')),
    sa.PrimaryKeyConstraint('question_id', 'category_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.drop_table('question_knowledge_points')
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_points_slug'))
        batch_op.drop_index(batch_op.f('ix_knowledge_points_name'))
        batch_op.drop_index(batch_op.f('ix_knowledge_points_id'))

    op.drop_table('knowledge_points')
    # ### end Alembic commands ###
