"""refactor_import_task_v2

Revision ID: cb5af9252eaf
Revises: a19fc2f7b6d0
Create Date: 2025-12-17 22:19:15.482407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb5af9252eaf'
down_revision: Union[str, Sequence[str], None] = 'a19fc2f7b6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Remove FK from questions first
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_task_id', sa.Integer(), nullable=True))
        # We need to know the name of the constraint to drop it. 
        # Alembic autogenerate guessed 'questions_ibfk_3', but let's be safe or trust it.
        # If it fails, we might need to inspect db.
        batch_op.drop_constraint('questions_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'import_tasks', ['import_task_id'], ['id'])
        batch_op.drop_column('import_batch_id')

    # 2. Modify import_tasks (remove FK to batches)
    with op.batch_alter_table('import_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        # Drop FK to import_batches
        batch_op.drop_constraint('import_tasks_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('batch_id')

    # 3. Now we can drop import_batches
    # with op.batch_alter_table('import_batches', schema=None) as batch_op:
    #    batch_op.drop_index(batch_op.f('ix_import_batches_id'))
    op.drop_table('import_batches')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_batch_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('questions_ibfk_3'), 'import_batches', ['import_batch_id'], ['id'])
        batch_op.drop_column('import_task_id')

    with op.batch_alter_table('import_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('import_tasks_ibfk_1'), 'import_batches', ['batch_id'], ['id'])
        batch_op.drop_column('source')
        batch_op.drop_column('description')
        batch_op.drop_column('user_id')

    op.create_table('import_batches',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'), nullable=True),
    sa.Column('total_files', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed_files', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('import_batches_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_id'), ['id'], unique=False)

    # ### end Alembic commands ###
