"""add_tag_category_table

Revision ID: daa91eaa10f8
Revises: add4a1d0b0b1
Create Date: 2025-12-14 13:29:09.617737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa91eaa10f8'
down_revision: Union[str, Sequence[str], None] = 'add4a1d0b0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_categories_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_tag_categories_id'))

    op.drop_table('tag_categories')
    # ### end Alembic commands ###
