"""Migration smoke tests (SQLite).

These run the real Alembic chain (not ``create_all``) so schema-level dialect
problems and model/migration drift surface in CI. MySQL is covered separately
in CI where a real server is available.
"""
import os

import pytest
from alembic import command
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine

from app.db.migrations import _alembic_config

# Set by the CI MySQL job to a real server; skipped locally when unset.
MYSQL_TEST_URL = os.getenv("MYSQL_TEST_URL")


def _sqlite_urls(tmp_path):
    db = tmp_path / "migrations.db"
    # async URL drives Alembic (env.py), sync URL is only for inspecting state.
    return f"sqlite+aiosqlite:///{db}", f"sqlite:///{db}"


def test_upgrade_head_on_empty_sqlite(tmp_path):
    async_url, sync_url = _sqlite_urls(tmp_path)
    cfg = _alembic_config(async_url)

    command.upgrade(cfg, "head")

    heads = set(ScriptDirectory.from_config(cfg).get_heads())
    engine = create_engine(sync_url)
    try:
        with engine.connect() as conn:
            current = set(MigrationContext.configure(conn).get_current_heads())
    finally:
        engine.dispose()
    assert current == heads


def test_no_model_migration_drift(tmp_path):
    async_url, _ = _sqlite_urls(tmp_path)
    cfg = _alembic_config(async_url)
    command.upgrade(cfg, "head")

    # Raises AutogenerateDiffsDetected if models diverge from the migration head.
    command.check(cfg)


@pytest.mark.skipif(not MYSQL_TEST_URL, reason="MYSQL_TEST_URL not set (needs a real MySQL)")
def test_upgrade_head_on_mysql():
    # Only a real MySQL exposes dialect-specific failures (types, ALTER, charset)
    # that SQLite cannot emulate; drift is already covered on SQLite above.
    command.upgrade(_alembic_config(MYSQL_TEST_URL), "head")
