"""add_is_embedding_model

Revision ID: 0173a4276270
Revises: a172b7091a8c
Create Date: 2025-12-17 10:28:10.792764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0173a4276270'
down_revision: Union[str, Sequence[str], None] = 'a172b7091a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_embedding_model', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.drop_column('is_embedding_model')

    # ### end Alembic commands ###
