"""change_question_status_to_string

Revision ID: 2a482b053acb
Revises: f6b25e7c3fc4
Create Date: 2025-12-12 10:22:44.666178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a482b053acb'
down_revision: Union[str, Sequence[str], None] = 'f6b25e7c3fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED'),
               existing_nullable=False)

    # ### end Alembic commands ###
