"""compositions folders blocks from papers

Revision ID: 680d028884fa
Revises: 326519e83a77
Create Date: 2026-08-17 17:38:05.543602

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680d028884fa'
down_revision: Union[str, Sequence[str], None] = '326519e83a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_folders_owner_id_user')),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], name=op.f('fk_folders_parent_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_folders_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders'))
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_folders_tree', ['subject_id', 'kind', 'scope'], unique=False)

    op.create_table('compositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('comp_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_compositions_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_compositions_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compositions'))
    )
    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compositions_comp_type'), ['comp_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_compositions_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compositions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compositions_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compositions_status'), ['status'], unique=False)

    op.create_table('composition_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('ref_question_id', sa.Integer(), nullable=True),
    sa.Column('ref_composition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composition_id'], ['compositions.id'], name=op.f('fk_composition_blocks_composition_id_compositions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_composition_id'], ['compositions.id'], name=op.f('fk_composition_blocks_ref_composition_id_compositions')),
    sa.ForeignKeyConstraint(['ref_question_id'], ['questions.id'], name=op.f('fk_composition_blocks_ref_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_composition_blocks'))
    )
    with op.batch_alter_table('composition_blocks', schema=None) as batch_op:
        batch_op.create_index('ix_comp_block_seq', ['composition_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_composition_blocks_composition_id'), ['composition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_composition_blocks_id'), ['id'], unique=False)

    # --- Data migration: papers/paper_questions -> compositions/composition_blocks ---
    bind = op.get_bind()

    folders_tbl = sa.table(
        'folders',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('parent_id', sa.Integer),
        sa.column('kind', sa.String),
        sa.column('scope', sa.String),
        sa.column('subject_id', sa.Integer),
        sa.column('owner_id', sa.Integer),
        sa.column('sequence', sa.Integer),
        sa.column('created_at', sa.String),
    )
    comps_tbl = sa.table(
        'compositions',
        sa.column('id', sa.Integer),
        sa.column('folder_id', sa.Integer),
        sa.column('comp_type', sa.String),
        sa.column('title', sa.String),
        sa.column('description', sa.Text),
        sa.column('status', sa.String),
        sa.column('difficulty', sa.Integer),
        sa.column('meta_data', sa.JSON),
        sa.column('owner_id', sa.Integer),
        sa.column('created_at', sa.String),
        sa.column('updated_at', sa.String),
    )
    blocks_tbl = sa.table(
        'composition_blocks',
        sa.column('composition_id', sa.Integer),
        sa.column('block_type', sa.String),
        sa.column('sequence', sa.Integer),
        sa.column('content', sa.JSON),
        sa.column('ref_question_id', sa.Integer),
        sa.column('ref_composition_id', sa.Integer),
    )

    papers = bind.execute(sa.text(
        "SELECT id, title, description, status, subject_id, owner_id, created_at, updated_at "
        "FROM papers ORDER BY id"
    )).fetchall()

    if papers:
        fallback_subject = bind.execute(sa.text("SELECT MIN(id) FROM subjects")).scalar()

        # 1) 为每个 (owner, subject) 建"个人·作品"根文件夹
        folder_rows = []
        folder_map = {}
        next_folder_id = 1
        for p in papers:
            subject_id = p.subject_id or fallback_subject
            if subject_id is None:
                continue
            key = (p.owner_id, subject_id)
            if key not in folder_map:
                folder_map[key] = next_folder_id
                folder_rows.append({
                    'id': next_folder_id,
                    'name': '我的试卷',
                    'parent_id': None,
                    'kind': 'deliverable',
                    'scope': 'personal',
                    'subject_id': subject_id,
                    'owner_id': p.owner_id,
                    'sequence': 0,
                    'created_at': datetime.utcnow().isoformat(sep=' '),
                })
                next_folder_id += 1
        if folder_rows:
            op.bulk_insert(folders_tbl, folder_rows)

        # 2) paper -> composition (保留 id 以便 blocks 对齐)
        comp_rows = []
        valid_paper_ids = set()
        for p in papers:
            subject_id = p.subject_id or fallback_subject
            if subject_id is None:
                continue
            comp_rows.append({
                'id': p.id,
                'folder_id': folder_map[(p.owner_id, subject_id)],
                'comp_type': 'exam_paper',
                'title': p.title,
                'description': p.description,
                'status': p.status or 'draft',
                'difficulty': None,
                'meta_data': None,
                'owner_id': p.owner_id,
                'created_at': p.created_at,
                'updated_at': p.updated_at,
            })
            valid_paper_ids.add(p.id)
        if comp_rows:
            op.bulk_insert(comps_tbl, comp_rows)

        # 3) paper_questions -> blocks (section_title -> heading, score -> content)
        items = bind.execute(sa.text(
            "SELECT paper_id, question_id, sequence, section_title, score "
            "FROM paper_questions ORDER BY paper_id, sequence"
        )).fetchall()
        block_rows = []
        current_paper = None
        seq = 0
        for it in items:
            if it.paper_id not in valid_paper_ids:
                continue
            if it.paper_id != current_paper:
                current_paper = it.paper_id
                seq = 0
            if it.section_title:
                block_rows.append({
                    'composition_id': it.paper_id,
                    'block_type': 'heading',
                    'sequence': seq,
                    'content': {'text': it.section_title, 'level': 2},
                    'ref_question_id': None,
                    'ref_composition_id': None,
                })
                seq += 1
            content = {'score': it.score} if it.score is not None else None
            block_rows.append({
                'composition_id': it.paper_id,
                'block_type': 'question',
                'sequence': seq,
                'content': content,
                'ref_question_id': it.question_id,
                'ref_composition_id': None,
            })
            seq += 1
        if block_rows:
            op.bulk_insert(blocks_tbl, block_rows)

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_id'))
        batch_op.drop_index(batch_op.f('ix_papers_owner_id'))

    op.drop_table('papers')
    with op.batch_alter_table('paper_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_questions_id'))
        batch_op.drop_index(batch_op.f('ix_paper_questions_paper_id'))
        batch_op.drop_index(batch_op.f('ix_paper_seq'))

    op.drop_table('paper_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('paper_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('sequence', sa.INTEGER(), nullable=False),
    sa.Column('section_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_questions_paper_id_publications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_paper_questions_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_questions'))
    )
    with op.batch_alter_table('paper_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_seq'), ['paper_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_questions_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_questions_id'), ['id'], unique=False)

    op.create_table('papers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_papers_owner_id_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_papers_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers'))
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_id'), ['id'], unique=False)

    with op.batch_alter_table('composition_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_composition_blocks_id'))
        batch_op.drop_index(batch_op.f('ix_composition_blocks_composition_id'))
        batch_op.drop_index('ix_comp_block_seq')

    op.drop_table('composition_blocks')
    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compositions_status'))
        batch_op.drop_index(batch_op.f('ix_compositions_owner_id'))
        batch_op.drop_index(batch_op.f('ix_compositions_id'))
        batch_op.drop_index(batch_op.f('ix_compositions_folder_id'))
        batch_op.drop_index(batch_op.f('ix_compositions_comp_type'))

    op.drop_table('compositions')
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index('ix_folders_tree')
        batch_op.drop_index(batch_op.f('ix_folders_subject_id'))
        batch_op.drop_index(batch_op.f('ix_folders_parent_id'))
        batch_op.drop_index(batch_op.f('ix_folders_owner_id'))
        batch_op.drop_index(batch_op.f('ix_folders_id'))

    op.drop_table('folders')
    # ### end Alembic commands ###
