"""assessment domain tables

Revision ID: 6f2d70c895a4
Revises: d4e5f6a7b8c9
Create Date: 2026-09-15 17:48:18.088948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2d70c895a4'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("revision >= 1", name=op.f('ck_assessments_assessment_revision_positive')),
    sa.CheckConstraint("status IN ('active', 'archived')", name=op.f('ck_assessments_assessment_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_assessments_created_by_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_assessments_subject_id_subjects')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_assessments_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_assessments_subject_status', ['subject_id', 'status'], unique=False)

    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_classrooms_created_by_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_classrooms_subject_id_subjects')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_classrooms_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classrooms')),
    sa.UniqueConstraint('subject_id', 'name', name='classroom_name_per_subject')
    )
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classrooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_subject_id'), ['subject_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('student_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_students_created_by_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_students_subject_id_subjects')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_students_updated_by_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_students_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('subject_id', 'student_no', name='student_no_per_subject'),
    sa.UniqueConstraint('subject_id', 'user_id', name='student_user_per_subject')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=False)

    op.create_table('classroom_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_classroom_students_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_classroom_students_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classroom_students')),
    sa.UniqueConstraint('classroom_id', 'student_id', name='student_per_classroom')
    )
    with op.batch_alter_table('classroom_students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_students_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_students_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_students_student_id'), ['student_id'], unique=False)

    op.create_table('assessment_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('composition_version_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('item_count > 0', name=op.f('ck_assessment_versions_assessment_version_item_count_positive')),
    sa.CheckConstraint('schema_version >= 1', name=op.f('ck_assessment_versions_assessment_version_schema_version_positive')),
    sa.CheckConstraint('total_score > 0', name=op.f('ck_assessment_versions_assessment_version_total_positive')),
    sa.CheckConstraint('version_no >= 1', name=op.f('ck_assessment_versions_assessment_version_no_positive')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_versions_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['composition_version_id'], ['composition_versions.id'], name=op.f('fk_assessment_versions_composition_version_id_composition_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_assessment_versions_created_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_versions')),
    sa.UniqueConstraint('assessment_id', 'version_no', name='assessment_version_no')
    )
    with op.batch_alter_table('assessment_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_versions_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_versions_composition_version_id'), ['composition_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_versions_id'), ['id'], unique=False)

    op.create_table('assessment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source_question_id', sa.Integer(), nullable=True),
    sa.Column('source_question_revision', sa.Integer(), nullable=True),
    sa.Column('source_node_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_snapshot', sa.JSON(), nullable=False),
    sa.Column('response_spec', sa.JSON(), nullable=False),
    sa.Column('scoring_spec', sa.JSON(), nullable=False),
    sa.Column('metadata_snapshot', sa.JSON(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_score > 0', name=op.f('ck_assessment_items_assessment_item_max_score_positive')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_assessment_items_assessment_item_position_non_negative')),
    sa.CheckConstraint('schema_version >= 1', name=op.f('ck_assessment_items_assessment_item_schema_version_positive')),
    sa.ForeignKeyConstraint(['parent_item_id'], ['assessment_items.id'], name=op.f('fk_assessment_items_parent_item_id_assessment_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.id'], name=op.f('fk_assessment_items_source_question_id_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['assessment_versions.id'], name=op.f('fk_assessment_items_version_id_assessment_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_items')),
    sa.UniqueConstraint('version_id', 'item_key', name='item_key_per_version')
    )
    with op.batch_alter_table('assessment_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_items_version_id'), ['version_id'], unique=False)
        batch_op.create_index('ix_assessment_items_version_pos', ['version_id', 'position'], unique=False)

    op.create_table('assessment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('grading_status', sa.String(length=20), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_limit', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('attempt_limit IS NULL OR attempt_limit >= 1', name=op.f('ck_assessment_sessions_assessment_session_attempt_limit_positive')),
    sa.CheckConstraint("delivery_status IN ('draft', 'open', 'closed')", name=op.f('ck_assessment_sessions_assessment_session_delivery_status_valid')),
    sa.CheckConstraint("grading_status IN ('not_started', 'in_progress', 'finalized')", name=op.f('ck_assessment_sessions_assessment_session_grading_status_valid')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_assessment_sessions_assessment_session_revision_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_assessment_sessions_created_by_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_assessment_sessions_subject_id_subjects')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_assessment_sessions_updated_by_user')),
    sa.ForeignKeyConstraint(['version_id'], ['assessment_versions.id'], name=op.f('fk_assessment_sessions_version_id_assessment_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_sessions'))
    )
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_sessions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_assessment_sessions_subject_status', ['subject_id', 'grading_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_sessions_version_id'), ['version_id'], unique=False)

    op.create_table('assessment_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_assessment_events_actor_id_user')),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.id'], name=op.f('fk_assessment_events_session_id_assessment_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_events')),
    sa.UniqueConstraint('session_id', 'batch_id', name='assessment_event_batch_per_session')
    )
    with op.batch_alter_table('assessment_events', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_events_actor_created', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_assessment_events_session', ['session_id', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_events_session_id'), ['session_id'], unique=False)

    op.create_table('assessment_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_key', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('identifier', sa.String(length=128), nullable=True),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("attendance_status IN ('present', 'absent', 'excused')", name=op.f('ck_assessment_participations_assessment_participation_attendance_valid')),
    sa.CheckConstraint("status IN ('invited', 'active', 'completed', 'withdrawn')", name=op.f('ck_assessment_participations_assessment_participation_status_valid')),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.id'], name=op.f('fk_assessment_participations_session_id_assessment_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_assessment_participations_student_id_students'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_assessment_participations_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_participations')),
    sa.UniqueConstraint('session_id', 'participant_key', name='participant_key_per_session')
    )
    with op.batch_alter_table('assessment_participations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_participations_id'), ['id'], unique=False)
        batch_op.create_index('ix_assessment_participations_session', ['session_id', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_participations_session_id'), ['session_id'], unique=False)

    op.create_table('assessment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participation_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('answered_count', sa.Integer(), nullable=False),
    sa.Column('graded_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.CheckConstraint('attempt_no >= 1', name=op.f('ck_assessment_attempts_assessment_attempt_no_positive')),
    sa.CheckConstraint('answered_count >= 0', name=op.f('ck_assessment_attempts_assessment_attempt_answered_count_non_negative')),
    sa.CheckConstraint('graded_count >= 0', name=op.f('ck_assessment_attempts_assessment_attempt_graded_count_non_negative')),
    sa.CheckConstraint('max_score IS NULL OR max_score >= 0', name=op.f('ck_assessment_attempts_assessment_attempt_max_non_negative')),
    sa.CheckConstraint("mode IN ('offline', 'online')", name=op.f('ck_assessment_attempts_assessment_attempt_mode_valid')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_assessment_attempts_assessment_attempt_revision_positive')),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'submitted', 'grading', 'graded', 'void')", name=op.f('ck_assessment_attempts_assessment_attempt_status_valid')),
    sa.CheckConstraint('total_score IS NULL OR total_score >= 0', name=op.f('ck_assessment_attempts_assessment_attempt_total_non_negative')),
    sa.ForeignKeyConstraint(['participation_id'], ['assessment_participations.id'], name=op.f('fk_assessment_attempts_participation_id_assessment_participations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_attempts')),
    sa.UniqueConstraint('participation_id', 'attempt_no', name='attempt_no_per_participation')
    )
    with op.batch_alter_table('assessment_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_attempts_id'), ['id'], unique=False)
        batch_op.create_index('ix_assessment_attempts_participation', ['participation_id', 'attempt_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_attempts_participation_id'), ['participation_id'], unique=False)

    op.create_table('assessment_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('answer_payload', sa.JSON(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_assessment_responses_assessment_response_revision_positive')),
    sa.CheckConstraint('schema_version >= 1', name=op.f('ck_assessment_responses_assessment_response_schema_version_positive')),
    sa.CheckConstraint("status IN ('unanswered', 'answered', 'omitted')", name=op.f('ck_assessment_responses_assessment_response_status_valid')),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], name=op.f('fk_assessment_responses_attempt_id_assessment_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_items.id'], name=op.f('fk_assessment_responses_item_id_assessment_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_responses')),
    sa.UniqueConstraint('attempt_id', 'item_id', name='response_per_attempt_item')
    )
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_responses_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_responses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_responses_item_id'), ['item_id'], unique=False)

    op.create_table('response_grades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grading_method', sa.String(length=20), nullable=False),
    sa.Column('grader_id', sa.Integer(), nullable=True),
    sa.Column('scoring_details', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=False),
    sa.Column('supersedes_grade_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_score >= 0', name=op.f('ck_response_grades_response_grade_max_score_non_negative')),
    sa.CheckConstraint("grading_method IN ('manual', 'imported', 'automatic', 'external')", name=op.f('ck_response_grades_response_grade_method_valid')),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('correct', 'partial', 'incorrect', 'unscored')", name=op.f('ck_response_grades_response_grade_outcome_valid')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_response_grades_response_grade_revision_positive')),
    sa.CheckConstraint('score IS NULL OR score <= max_score', name=op.f('ck_response_grades_response_grade_score_le_max')),
    sa.CheckConstraint('score IS NULL OR score >= 0', name=op.f('ck_response_grades_response_grade_score_non_negative')),
    sa.CheckConstraint("status IN ('pending', 'graded', 'invalidated')", name=op.f('ck_response_grades_response_grade_status_valid')),
    sa.ForeignKeyConstraint(['grader_id'], ['user.id'], name=op.f('fk_response_grades_grader_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['assessment_responses.id'], name=op.f('fk_response_grades_response_id_assessment_responses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_grade_id'], ['response_grades.id'], name=op.f('fk_response_grades_supersedes_grade_id_response_grades'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_response_grades')),
    sa.UniqueConstraint('response_id', 'revision', name='grade_revision_per_response')
    )
    with op.batch_alter_table('response_grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_grades_response_id'), ['response_id'], unique=False)
        batch_op.create_index('ix_response_grades_response_rev', ['response_id', 'revision'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_grades', schema=None) as batch_op:
        batch_op.drop_index('ix_response_grades_response_rev')
        batch_op.drop_index(batch_op.f('ix_response_grades_response_id'))

    op.drop_table('response_grades')
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_responses_item_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_responses_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_responses_attempt_id'))

    op.drop_table('assessment_responses')
    with op.batch_alter_table('assessment_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_attempts_participation_id'))
        batch_op.drop_index('ix_assessment_attempts_participation')
        batch_op.drop_index(batch_op.f('ix_assessment_attempts_id'))

    op.drop_table('assessment_attempts')
    with op.batch_alter_table('assessment_participations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_participations_session_id'))
        batch_op.drop_index('ix_assessment_participations_session')
        batch_op.drop_index(batch_op.f('ix_assessment_participations_id'))

    op.drop_table('assessment_participations')
    with op.batch_alter_table('assessment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_events_session_id'))
        batch_op.drop_index('ix_assessment_events_session')
        batch_op.drop_index('ix_assessment_events_actor_created')

    op.drop_table('assessment_events')
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_version_id'))
        batch_op.drop_index('ix_assessment_sessions_subject_status')
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_id'))

    op.drop_table('assessment_sessions')
    with op.batch_alter_table('assessment_items', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_items_version_pos')
        batch_op.drop_index(batch_op.f('ix_assessment_items_version_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_items_id'))

    op.drop_table('assessment_items')
    with op.batch_alter_table('assessment_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_versions_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_versions_composition_version_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_versions_assessment_id'))

    op.drop_table('assessment_versions')
    with op.batch_alter_table('classroom_students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_students_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_students_classroom_id'))

    op.drop_table('classroom_students')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_subject_id'))
        batch_op.drop_index(batch_op.f('ix_students_id'))

    op.drop_table('students')
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classrooms_subject_id'))
        batch_op.drop_index(batch_op.f('ix_classrooms_id'))

    op.drop_table('classrooms')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_assessments_subject_status')
        batch_op.drop_index(batch_op.f('ix_assessments_subject_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_id'))

    op.drop_table('assessments')
    # ### end Alembic commands ###
