"""add_import_tasks

Revision ID: 72f41c888c6a
Revises: c7ae97d0807a
Create Date: 2025-12-17 17:55:11.972132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '72f41c888c6a'
down_revision: Union[str, Sequence[str], None] = 'c7ae97d0807a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_tasks_status'), ['status'], unique=False)

    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='batchstatus'), nullable=True))
        batch_op.add_column(sa.Column('total_files', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_files', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('total_count')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('processed_files')
        batch_op.drop_column('total_files')
        batch_op.drop_column('status')

    with op.batch_alter_table('import_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_import_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_import_tasks_created_at'))

    op.drop_table('import_tasks')
    # ### end Alembic commands ###
