"""add subject settings table

Revision ID: 842a88641edd
Revises: b9d5f0a21c3e
Create Date: 2026-09-21 22:40:19.961610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842a88641edd'
down_revision: Union[str, Sequence[str], None] = 'b9d5f0a21c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_subject_settings_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_settings')),
    sa.UniqueConstraint('subject_id', 'key', name='uq_subject_settings_subject_id_key')
    )
    with op.batch_alter_table('subject_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_settings_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_settings_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_settings_subject_id'))
        batch_op.drop_index(batch_op.f('ix_subject_settings_key'))
        batch_op.drop_index(batch_op.f('ix_subject_settings_id'))

    op.drop_table('subject_settings')
    # ### end Alembic commands ###
