"""add question groups and relations

Revision ID: 9417bea9971b
Revises: b7c1e94d2a35
Create Date: 2026-09-19 21:19:50.988693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9417bea9971b'
down_revision: Union[str, Sequence[str], None] = 'b7c1e94d2a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stimuli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('content', mysql.LONGTEXT().with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', mysql.LONGTEXT().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_stimuli_created_by_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_stimuli_subject_id_subjects')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_stimuli_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stimuli'))
    )
    with op.batch_alter_table('stimuli', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stimuli_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stimuli_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stimuli_subject_id'), ['subject_id'], unique=False)

    op.create_table('question_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('stimulus_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', mysql.LONGTEXT().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_question_groups_created_by_user')),
    sa.ForeignKeyConstraint(['stimulus_id'], ['stimuli.id'], name=op.f('fk_question_groups_stimulus_id_stimuli')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_question_groups_subject_id_subjects')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_question_groups_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_groups'))
    )
    with op.batch_alter_table('question_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_groups_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_groups_stimulus_id'), ['stimulus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_groups_subject_id'), ['subject_id'], unique=False)

    op.create_table('question_group_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_question_group_items_position_non_negative')),
    sa.ForeignKeyConstraint(['group_id'], ['question_groups.id'], name=op.f('fk_question_group_items_group_id_question_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_group_items_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_group_items')),
    sa.UniqueConstraint('group_id', 'position', name='uq_question_group_items_position'),
    sa.UniqueConstraint('group_id', 'question_id', name='uq_question_group_items_question')
    )
    op.create_table('question_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_question_id', sa.Integer(), nullable=False),
    sa.Column('target_question_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('source_question_id <> target_question_id', name=op.f('ck_question_relations_different_questions')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_question_relations_created_by_user')),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.id'], name=op.f('fk_question_relations_source_question_id_questions')),
    sa.ForeignKeyConstraint(['target_question_id'], ['questions.id'], name=op.f('fk_question_relations_target_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_relations')),
    sa.UniqueConstraint('source_question_id', 'target_question_id', 'relation_type', name='uq_question_relations_edge')
    )
    # Legacy parent_id points child -> parent. The relation graph points source
    # (original parent) -> target (decomposed child); no groups are inferred.
    op.execute(
        sa.text(
            """
            INSERT INTO question_relations
                (source_question_id, target_question_id, relation_type, created_at, created_by)
            SELECT parent_id, id, 'decomposed_from', CURRENT_TIMESTAMP, created_by
            FROM questions AS child
            WHERE parent_id IS NOT NULL
              AND parent_id <> id
                            AND EXISTS (
                                    SELECT 1
                                    FROM questions AS parent
                                    WHERE parent.id = child.parent_id
                                        AND (
                                                parent.subject_id = child.subject_id
                                                OR (
                                                        parent.subject_id IS NULL
                                                        AND child.subject_id IS NULL
                                                )
                                        )
                            )
              AND NOT EXISTS (
                  SELECT 1
                  FROM question_relations AS relation
                  WHERE relation.source_question_id = child.parent_id
                    AND relation.target_question_id = child.id
                    AND relation.relation_type = 'decomposed_from'
              )
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop tables in dependency order. Explicit index drops fail on MySQL when
    # an index is still required by a foreign key; dropping the table removes
    # its indexes and constraints together. Existence checks also make recovery
    # safe after a non-transactional MySQL downgrade stopped midway.
    inspector = sa.inspect(op.get_bind())
    for table_name in (
        "question_relations",
        "question_group_items",
        "question_groups",
        "stimuli",
    ):
        if inspector.has_table(table_name):
            op.drop_table(table_name)
