"""add cascade delete to knowledge points

Revision ID: c7ae97d0807a
Revises: 446dd8221fbc
Create Date: 2025-12-17 15:12:39.021441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ae97d0807a'
down_revision: Union[str, Sequence[str], None] = '446dd8221fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('knowledge_points_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'knowledge_points', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('knowledge_points_ibfk_2'), 'knowledge_points', ['parent_id'], ['id'])

    # ### end Alembic commands ###
