"""add subject_prompts table

Revision ID: cc9f4fd05314
Revises: e428d31b27cb
Create Date: 2026-08-14 17:31:00.769326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9f4fd05314'
down_revision: Union[str, Sequence[str], None] = 'e428d31b27cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_subject_prompts_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_prompts')),
    sa.UniqueConstraint('subject_id', 'key', name='uq_subject_prompts_subject_id_key')
    )
    with op.batch_alter_table('subject_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_prompts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_prompts_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_prompts_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_prompts_subject_id'))
        batch_op.drop_index(batch_op.f('ix_subject_prompts_key'))
        batch_op.drop_index(batch_op.f('ix_subject_prompts_id'))

    op.drop_table('subject_prompts')
    # ### end Alembic commands ###
