"""add papers and paper_questions tables

Revision ID: cd840eec8ffb
Revises: 72b8e310399b
Create Date: 2026-08-02 16:43:14.776088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd840eec8ffb'
down_revision: Union[str, Sequence[str], None] = '72b8e310399b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_owner_id'), ['owner_id'], unique=False)

    op.create_table('paper_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_questions_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index('ix_paper_seq', ['paper_id', 'sequence'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_paper_seq')
        batch_op.drop_index(batch_op.f('ix_paper_questions_paper_id'))
        batch_op.drop_index(batch_op.f('ix_paper_questions_id'))

    op.drop_table('paper_questions')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_papers_id'))

    op.drop_table('papers')
    # ### end Alembic commands ###
