"""add_subject_id_to_tag_categories

Revision ID: d6dad2112494
Revises: be950d8c78c6
Create Date: 2026-08-06 21:20:59.872971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6dad2112494'
down_revision: Union[str, Sequence[str], None] = 'be950d8c78c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 获取数据库连接以执迁移数据
    conn = op.get_bind()
    
    # 1. 结构变更：添加字段和索引
    with op.batch_alter_table('tag_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_tag_categories_slug'))
        batch_op.create_index(batch_op.f('ix_tag_categories_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_categories_subject_id'), ['subject_id'], unique=False)
        batch_op.create_foreign_key('fk_tag_categories_subjects', 'subjects', ['subject_id'], ['id'])

    # 2. 数据迁移：为每个subject复制全局tag_categories
    # 获取所有的 subjects
    subjects_rs = conn.execute(sa.text("SELECT id FROM subjects"))
    subjects = [row[0] for row in subjects_rs]

    # 获取当前所有全局 tag_categories
    categories_rs = conn.execute(sa.text("SELECT id, name, slug, sort_order, is_active FROM tag_categories WHERE subject_id IS NULL"))
    categories = [row for row in categories_rs]

    # 执行复制插入
    for subject_id in subjects:
        for cat in categories:
            cat_id, name, slug, sort_order, is_active = cat
            conn.execute(sa.text(
                "INSERT INTO tag_categories (name, slug, sort_order, is_active, subject_id) "
                "VALUES (:name, :slug, :sort_order, :is_active, :subject_id)"
            ).bindparams(name=name, slug=slug, sort_order=sort_order, is_active=is_active, subject_id=subject_id))
            
    # 删除旧的全局记录
    conn.execute(sa.text("DELETE FROM tag_categories WHERE subject_id IS NULL"))
    
    # 3. 添加联合唯一约束并修改非空
    with op.batch_alter_table('tag_categories', schema=None) as batch_op:
        batch_op.alter_column('subject_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_unique_constraint('uq_tag_category_subject_name', ['subject_id', 'name'])
        batch_op.create_unique_constraint('uq_tag_category_subject_slug', ['subject_id', 'slug'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_tag_category_subject_slug', type_='unique')
        batch_op.drop_constraint('uq_tag_category_subject_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_tag_categories_subject_id'))
        batch_op.drop_index(batch_op.f('ix_tag_categories_slug'))
        batch_op.create_index(batch_op.f('ix_tag_categories_slug'), ['slug'], unique=True)
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
