"""add assessment gradebook tables

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2026-09-14 20:40:52.136902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f6a7b8c9d0'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_classrooms_created_by_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_classrooms_subject_id_subjects')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_classrooms_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classrooms')),
    sa.UniqueConstraint('subject_id', 'name', name='classroom_name_per_subject')
    )
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classrooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_subject_id'), ['subject_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('student_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_students_created_by_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_students_subject_id_subjects')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_students_updated_by_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_students_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('subject_id', 'student_no', name='student_no_per_subject'),
    sa.UniqueConstraint('subject_id', 'user_id', name='student_user_per_subject')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=False)

    op.create_table('classroom_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_classroom_students_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_classroom_students_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classroom_students')),
    sa.UniqueConstraint('classroom_id', 'student_id', name='student_per_classroom')
    )
    with op.batch_alter_table('classroom_students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_students_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_students_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_students_student_id'), ['student_id'], unique=False)

    op.create_table('exam_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('composition_version_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('total_score > 0', name=op.f('ck_exam_sessions_total_score_positive')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_exam_sessions_exam_session_revision_positive')),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_exam_sessions_classroom_id_classrooms')),
    sa.ForeignKeyConstraint(['composition_version_id'], ['composition_versions.id'], name=op.f('fk_exam_sessions_composition_version_id_composition_versions')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_exam_sessions_created_by_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_exam_sessions_subject_id_subjects')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_exam_sessions_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_sessions'))
    )
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_sessions_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_sessions_composition_version_id'), ['composition_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_sessions_id'), ['id'], unique=False)
        batch_op.create_index('ix_exam_sessions_subject_classroom', ['subject_id', 'classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_sessions_subject_id'), ['subject_id'], unique=False)

    op.create_table('exam_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('exam_session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_exam_events_actor_id_user')),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], name=op.f('fk_exam_events_exam_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_events')),
    sa.UniqueConstraint('exam_session_id', 'batch_id', name='exam_event_batch_per_session')
    )
    with op.batch_alter_table('exam_events', schema=None) as batch_op:
        batch_op.create_index('ix_exam_events_actor_created', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_events_exam_session_id'), ['exam_session_id'], unique=False)
        batch_op.create_index('ix_exam_events_session_id', ['exam_session_id', 'id'], unique=False)

    op.create_table('exam_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('student_no', sa.String(length=64), nullable=False),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], name=op.f('fk_exam_participants_exam_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_exam_participants_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_participants')),
    sa.UniqueConstraint('exam_session_id', 'student_id', name='participant_per_session')
    )
    with op.batch_alter_table('exam_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_participants_exam_session_id'), ['exam_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_participants_id'), ['id'], unique=False)
        batch_op.create_index('ix_exam_participants_session', ['exam_session_id', 'id'], unique=False)

    op.create_table('exam_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_session_id', sa.Integer(), nullable=False),
    sa.Column('composition_node_id', sa.String(length=36), nullable=False),
    sa.Column('q_type', sa.String(length=64), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_score > 0', name=op.f('ck_exam_questions_max_score_positive')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_exam_questions_position_non_negative')),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], name=op.f('fk_exam_questions_exam_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_questions')),
    sa.UniqueConstraint('exam_session_id', 'composition_node_id', name='question_per_session')
    )
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_questions_exam_session_id'), ['exam_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_questions_id'), ['id'], unique=False)
        batch_op.create_index('ix_exam_questions_session_pos', ['exam_session_id', 'position'], unique=False)

    op.create_table('exam_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_exam_results_revision_positive')),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], name=op.f('fk_exam_results_exam_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['exam_participants.id'], name=op.f('fk_exam_results_participant_id_exam_participants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_results')),
    sa.UniqueConstraint('participant_id', name='result_per_participant')
    )
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_results_exam_session_id'), ['exam_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_results_participant_id'), ['participant_id'], unique=False)

    op.create_table('exam_score_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_result_id', sa.Integer(), nullable=False),
    sa.Column('exam_question_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('score IS NULL OR score >= 0', name=op.f('ck_exam_score_items_score_non_negative')),
    sa.ForeignKeyConstraint(['exam_question_id'], ['exam_questions.id'], name=op.f('fk_exam_score_items_exam_question_id_exam_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_result_id'], ['exam_results.id'], name=op.f('fk_exam_score_items_exam_result_id_exam_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_score_items')),
    sa.UniqueConstraint('exam_result_id', 'exam_question_id', name='score_per_result_question')
    )
    with op.batch_alter_table('exam_score_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_score_items_exam_question_id'), ['exam_question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_score_items_exam_result_id'), ['exam_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_score_items_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_score_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_score_items_id'))
        batch_op.drop_index(batch_op.f('ix_exam_score_items_exam_result_id'))
        batch_op.drop_index(batch_op.f('ix_exam_score_items_exam_question_id'))

    op.drop_table('exam_score_items')
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_results_participant_id'))
        batch_op.drop_index(batch_op.f('ix_exam_results_id'))
        batch_op.drop_index(batch_op.f('ix_exam_results_exam_session_id'))

    op.drop_table('exam_results')
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_exam_questions_session_pos')
        batch_op.drop_index(batch_op.f('ix_exam_questions_id'))
        batch_op.drop_index(batch_op.f('ix_exam_questions_exam_session_id'))

    op.drop_table('exam_questions')
    with op.batch_alter_table('exam_participants', schema=None) as batch_op:
        batch_op.drop_index('ix_exam_participants_session')
        batch_op.drop_index(batch_op.f('ix_exam_participants_id'))
        batch_op.drop_index(batch_op.f('ix_exam_participants_exam_session_id'))

    op.drop_table('exam_participants')
    with op.batch_alter_table('exam_events', schema=None) as batch_op:
        batch_op.drop_index('ix_exam_events_session_id')
        batch_op.drop_index(batch_op.f('ix_exam_events_exam_session_id'))
        batch_op.drop_index('ix_exam_events_actor_created')

    op.drop_table('exam_events')
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_sessions_subject_id'))
        batch_op.drop_index('ix_exam_sessions_subject_classroom')
        batch_op.drop_index(batch_op.f('ix_exam_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_exam_sessions_composition_version_id'))
        batch_op.drop_index(batch_op.f('ix_exam_sessions_classroom_id'))

    op.drop_table('exam_sessions')
    with op.batch_alter_table('classroom_students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_students_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_students_classroom_id'))

    op.drop_table('classroom_students')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_subject_id'))
        batch_op.drop_index(batch_op.f('ix_students_id'))

    op.drop_table('students')
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classrooms_subject_id'))
        batch_op.drop_index(batch_op.f('ix_classrooms_id'))

    op.drop_table('classrooms')
    # ### end Alembic commands ###
