"""update_question_type_enum

Revision ID: f02a7f680a4b
Revises: 22915b61a20a
Create Date: 2025-12-22 16:17:56.034410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02a7f680a4b'
down_revision: Union[str, Sequence[str], None] = '22915b61a20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'q_type',
               existing_type=sa.Enum('single_choice', 'multiple_choice', 'true_false', 'short_answer', name='questiontype'),
               type_=sa.Enum('single_choice', 'multiple_choice', 'true_false', 'fill_in_the_blank', 'free_response', name='questiontype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'q_type',
               existing_type=sa.Enum('single_choice', 'multiple_choice', 'true_false', 'fill_in_the_blank', 'free_response', name='questiontype'),
               type_=sa.Enum('single_choice', 'multiple_choice', 'true_false', 'short_answer', name='questiontype'),
               existing_nullable=False)
    # ### end Alembic commands ###
